name: Test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  avoid_reduncy:
    name: Cancel previous redundant builds
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

  # Temporarily disabled due to incompatibility with private methods        
  # lint:
  #   needs: [install_dependencies]
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout git repository
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Set up node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: Cache dependencies
  #       id: cache-dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: ./node_modules
  #         key: modules-${{ hashFiles('package-lock.json') }}

  #     - name: Install dependencies
  #       if: steps.cache-dependencies.outputs.cache-hit != 'true'
  #       run: npm ci --ignore-scripts 

  #     - name: Lint
  #       run: npm run eslint

  test:
    needs: [install_dependencies]
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts 

      - name: Test & coverage
        run: npm run test:coverage